Document: vtk8
Title: Debian vtk8 Manual
Author: <insert document author here>
Abstract: This manual describes what vtk8 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vtk8/vtk8.sgml.gz

Format: postscript
Files: /usr/share/doc/vtk8/vtk8.ps.gz

Format: text
Files: /usr/share/doc/vtk8/vtk8.text.gz

Format: HTML
Index: /usr/share/doc/vtk8/html/index.html
Files: /usr/share/doc/vtk8/html/*.html
